data:
  raw_path: "data/raw/dataset.csv"
  processed_path: "data/processed/"
models:
  dir: "/Users/ihack-pc/Downloads/Projects/Privacy-Preserving-NLP-through-Federated-learning-for-Medical-text-analysis/Jupyter Notebook/archive/federated_training_20241110_142938/"
  model_file: "final_model.pth"
  vectorizer_file: "vectorizer.pkl"
  label_encoder_file: "label_encoder.pkl"
training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 10
deployment:
  device: "cpu"

